### ISSUE TITLE
Cambiare sfondo file 8746

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#1]

**Comment by annapiera** [comment]
![8647](https://user-images.githubusercontent.com/47472672/52521663-d0124000-2c7a-11e9-99e0-00b4f10f0353.jpg)

**Comment by arialdomartini** [comment]
@annapiera, dunque, io lo sfondo l'ho messo (lo trovi online), ma vedo 2 problemi:

1. è uno sfondo bianco, per cui bisognerebbe cambiare il colore ai testi e alla barra dell'header, altrimenti appare così:

![screen shot 2019-02-09 at 19 05 11](https://user-images.githubusercontent.com/150719/52524474-b2a29d80-2c9d-11e9-9088-6322ec9c2bd6.png)

Ho messo dei testi neri giusto per riuscire a leggerli.

2. È un'immagine un po' fredda. La filosofia della uncoference ruota tutta intorno alla comunicazione, alle persone, agli scambi umani. Non sono sicuro che un'immagine geometrica sia il massimo, per quanto bella. Non è meglio mostrare delle persone, magari recuperando dalle foto degli scorsi anni?

**Comment by annapiera** [comment]
Ci ho pensato anche io, ma dimentichi la GDPR...
Possiamo trovare altro : )

**Comment by annapiera** [comment]
https://pixabay.com/it/idea-brainstorming-lavoro-di-squadra-2654150/
Questa? :D

**Comment by arialdomartini** [comment]
Molto meglio. Ha purtroppo un problema: ha molto bianco nel mezzo, per cui confonde la lettura del titolo. Non trovi? Se confronti con il sito della Francia, ci si accorge che lì il testo si legge bene, da noi un po' peggio... 
Ma mi piace molto l'idea di vedere gente che collabora.
Altre possibilità potrebbero essere:

- posso provare a scurire quella foto, o a sfocarla
- foto di Rimini
- foto dell'albergo (quelle con la piscina non sono male)
- altre foto di gente che lavora

**Comment by arialdomartini** [comment]
![screen shot 2019-02-09 at 22 00 29](https://user-images.githubusercontent.com/150719/52526258-281a6800-2cb6-11e9-841a-7b862c1571cf.png)

![screen shot 2019-02-09 at 22 24 00](https://user-images.githubusercontent.com/150719/52526471-70875500-2cb9-11e9-87a8-0123b9b9779b.png)


![screen shot 2019-02-09 at 22 15 38](https://user-images.githubusercontent.com/150719/52526398-43867280-2cb8-11e9-94f6-2c7228c36bb3.png)

![screen shot 2019-02-09 at 22 20 20](https://user-images.githubusercontent.com/150719/52526436-eb03a500-2cb8-11e9-9145-6aac66821896.png)

**Comment by arialdomartini** [comment]
Altrimenti, posso mettere un bordino intorno alle lettere così da aumentarne il contrasto. Il risultato è questo

![screen shot 2019-02-09 at 22 21 55](https://user-images.githubusercontent.com/150719/52526462-446bd400-2cb9-11e9-8862-b6b766309553.png)

**Comment by annapiera** [comment]
Mmmh. Mettere una maschera sulla foto, no?

Comunque ne possiamo cercare altre più scure

Poi mi spieghi il nesso tra le mappe antiche, i ponti romani e l’evento :’D

**Comment by arialdomartini** [comment]
Sono tutte immagini di Rimini.

**Comment by annapiera** [comment]
![startup-593343_1920](https://user-images.githubusercontent.com/47472672/52536883-679d8e80-2d60-11e9-8cfa-d6e46e1724fc.jpg)
![startup-593343_1920_v3](https://user-images.githubusercontent.com/47472672/52536895-961b6980-2d60-11e9-8d84-145d7f3be39a.jpg)
![startup-593343_1920_v2](https://user-images.githubusercontent.com/47472672/52536896-961b6980-2d60-11e9-83c5-431bbd048d8d.jpg)
Et voilà, prova con queste.
Il testo da bianco >> scuro

E SOCRATES IT verde!

**Comment by arialdomartini** [comment]
Ho provato.
Dunque, la più decente mi sembra con l'immagine scura


![screen shot 2019-02-10 at 22 55 09](https://user-images.githubusercontent.com/150719/52540177-f4f3d980-2d86-11e9-9843-ede7cbac19f2.png)

Peccato, perché l'immagine scura è meno brillante, meno bella.
Ma con l'immagine chiara non va proprio. Ho tentato con un pannello dietro, ma diventa un po' più pesante:

![screen shot 2019-02-10 at 22 49 54](https://user-images.githubusercontent.com/150719/52540188-1e146a00-2d87-11e9-8d66-b345f00a8a96.png)

Il testo in verde è proprio brutto....

L'ideale sarebbe trovare un'immagine non bianca, ma naturalmente più scura, non sbiadita. Mi piace molto l'effetto che viene nel sito del Belgio

![screen shot 2019-02-10 at 22 57 02](https://user-images.githubusercontent.com/150719/52540209-4ef49f00-2d87-11e9-8751-5c707873557f.png)

Io andrei con l'immagine scura, la prima di questo esempio.

**Comment by arialdomartini** [comment]
Forse separerei anche data e sottotitolo

**Comment by arialdomartini** [comment]
Viene così:

![screen shot 2019-02-10 at 23 11 10](https://user-images.githubusercontent.com/150719/52540386-2ec5df80-2d89-11e9-9c16-2df09d02f2f9.png)

**Comment by annapiera** [comment]
Io direi che com’è ora va bene. Chiudo! :)
