### ISSUE TITLE
 Cambiare colori: verde, rosso, bianco e nero

### ISSUE THREAD

**Issue by arialdomartini** [socrates-it-test/site-source#11]

**Comment by arialdomartini** [comment]
Non ho capito. Quali? Mi dici a voce appena ci vediamo?

**Comment by annapiera** [comment]
Era un task di indicazioni generale :D
Il giallo del sito di base va sostituito con questi :)

**Comment by annapiera** [comment]
@arialdomartini questa puoi chiuderla? 
Io non posso.
Insomma, abbiamo capito i colori :D

**Comment by annapiera** [comment]
Memento: eliminare il giallo da ovunque 
CTA nell'header e Box description

**Comment by arialdomartini** [comment]
Il background dei 2 CTA in home page e i background delle immagini nella sezione About quando ci passi sopra il mouse adesso sono verdi.
Ho messo tutto online. Da ora, per sincronizzarci, prima aggiorno online, poi aggiorno le issue su GitHub, così che le modifiche siano immediatamente visiili.

**Comment by annapiera** [comment]
Perfetto!
Chiudo. : )
