### ISSUE TITLE
privacy policy

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#13]

**Comment by arialdomartini** [comment]
Fatta. La Privacy Policy è linkata nel footer. Ci ho messo un lorem ipsum. Ci vuole un testo a modo.

**Comment by arialdomartini** [comment]
CI pensi tu al testo, @annapiera?

**Comment by annapiera** [comment]
Ci sto lavorando, ma prima di pubblicarla la sottopongo agli altri, perché ci saranno i nostri nomi non essendo una “società”

**Comment by annapiera** [comment]
@arialdomartini ti ho inviato il documento per e-mail, ma lo rimetto qui per sicurezza
[Privacy policy - Socrates IT 2019.docx](https://github.com/socrates-it-test/site-source/files/2907319/Privacy.policy.-.Socrates.IT.2019.docx)

Credo comunque sia da far leggere e approvare.

**Comment by annapiera** [comment]
Arialdo! 

![image](https://user-images.githubusercontent.com/47472672/53518539-92fada00-3ad1-11e9-9070-75eea66fa1a7.png)
Si è eliminato l'elenco puntato, why?

**Comment by annapiera** [comment]
La (c) si è digievoluta...

![image](https://user-images.githubusercontent.com/47472672/53518636-bfaef180-3ad1-11e9-98b2-f7896c0b7b56.png)

**Comment by arialdomartini** [comment]
Ah, ok! Vedo tutto!
Ho corretto. Ho messo un elenco puntato al posto di a) b) e c). Spero non sia un problema.

**Comment by annapiera** [comment]
Va benone! : )
Chiudo
