### ISSUE TITLE
[MENU] cambiare "Socrates IT" verde, no corsivo, uppercase, helvetica neue

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#15]

**Comment by annapiera** [comment]
#15 Davanti al nome "SOCRATES IT" inserire il logo italiano

**Comment by annapiera** [comment]
#15 Quando i nomi delle tab nel menu si "attivano" prego cambiare il giallo con il rosso.

**Comment by arialdomartini** [comment]
Sul serio ti piace uppercase??

![screen shot 2019-02-11 at 19 43 31](https://user-images.githubusercontent.com/150719/52585559-67bb8e00-2e35-11e9-8206-7e527d36354c.png)

**Comment by annapiera** [comment]
Sul serio, adoro! 
La “I” è un po’ fastidiosa, non trovi? 

Comunque mi piace così! a te no? 😂
È bello bold, fammi fare la markettara! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by annapiera** [comment]
Qui manca solo questo: il logo davanti al nome dell’evento: https://github.com/socrates-it-test/site-source/issues/15#issuecomment-462068232

**Comment by arialdomartini** [comment]
Strana la I
A me compare così

![deepinscreenshot_select-area_20190216115721](https://user-images.githubusercontent.com/150719/52898762-15d28980-31e2-11e9-9483-405cb0aefa08.png)

**Comment by arialdomartini** [comment]
@annapiera  dove devo mettere il logo?

**Comment by annapiera** [comment]
> Strana la I
> A me compare così
> 
> ![deepinscreenshot_select-area_20190216115721](https://user-images.githubusercontent.com/150719/52898762-15d28980-31e2-11e9-9483-405cb0aefa08.png)

La I si è modificata in meglio da sola.
Va bene così. : )

**Comment by annapiera** [comment]
> @annapiera dove devo mettere il logo?

Il logo lo mettiamo nel Menu, davanti alla scritta Socrates.
#10

**Comment by annapiera** [comment]
![image](https://user-images.githubusercontent.com/47472672/52900529-378a3b80-31f7-11e9-852a-2b2d001eca12.png)

**Comment by arialdomartini** [comment]
Aggiunto il logo. Non ho capito come ridurlo di dimensione quando si scrolla verso il basso. Ho aperto la issue #28.

**Comment by annapiera** [comment]
Chiudo, ormai il css non ha più misteri per te @arialdomartini ! 🎉🎉🎉
