### ISSUE TITLE
[TAB 5] Solo CTA

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#18]
Inserire CTA "register now", come le altre rossa, etc.

La CTA rimanderà alla pagina "registration"

**Comment by arialdomartini** [comment]
Questa dovrebbe essere un duplicato di #7, no?

**Comment by annapiera** [comment]
Nope, mi riferisco alla quinta tab.

Vedi qui: https://github.com/socrates-it-test/site-source/blob/master/docs/appunti.md

**Comment by arialdomartini** [comment]
Fatto.

**Comment by annapiera** [comment]
🎉🎉🎉
