### ISSUE TITLE
Sponsor

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#19]
Centrato: SPONSORSHIP

Do you want to support the event?
It would be great to list your company among our sponsors! Please **contact us** and we’ll send you the sponsorship prospect.

Inserire su "contact us" un mailto:nonsoqualeemail

**Comment by annapiera** [comment]
mettere sopra #20

**Comment by arialdomartini** [comment]
Ok, fatto. Per adesso ho messo come email il gruppo su Google Groups.
Penso che sia però da chiedere a Gabriele se ci sia una mail. Ci pensi tu?

Altra cosa: per il link nella sezione Sponsorship abbiamo 3 strada

- metto un link "contact us" con il link alla mail, come dici tu. Il problema è che non tutti hanno un software di mail che gestisca quel link. C'è il rischio che uno clicchi e non accada nulla. Se è abbastanza smaliziato, guarda a cosa punta il link e scopre quale sia la mail. Ma potrebbe essere più semplice andare sulla seconda opzione

- invece del testo "contact us" metterei direttamente la mail. Adesso online c'è questa opzione. Se non ti piace, la modifico

- invece del link potremmo avere un form. Svantaggi: devo svilupparla, non è lunghissimo ma qualche tempo ci vuole. Ci sta che ci arrivi un po' di spam.

**Comment by annapiera** [comment]
Alloorrr. 
Ho visto come l'hai impostato ora, è semplice, potrebbe andare bene.

Se vuoi fare il contact form nel template iniziale c'è già il contact form pronto:
https://themes.gohugo.io/airspace-hugo

Complicato? Che ne dici?

**Comment by arialdomartini** [comment]
Sì sì, mettere un form non è difficile. Non c'è nemmeno bisogno di prenderlo da Hugo, si può farlo in HTML direttamente.
Il problema è che dietro non abbiamo un backend. Per cui, dovremmo poggiarsi a servizi come https://formkeep.com/
Mi consulto con gli altri.

@VenomAV, tu come faresti?

**Comment by annapiera** [comment]
Update:
- niente contact form
- attesa risposta per connexxo

**Comment by arialdomartini** [comment]
Che famo con la GDPR?
