### ISSUE TITLE
[TAB 8] PARTNER

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#20]
In questa tab inseriamo tutti gli eventi dei socrates nel mondo con relativi link
Sono 11 in totale, quindi riusciamo a inserirle in due colonne? 
Una da 5 e l'altra da 4? 

SoCraTes Conference Switzerland 
SoCraTes Day Switzerland 
SoCraTes Canaries 
SoCraTes UK 
SoCraTes BE 
SoCraTes Soltau
SoCraTes France 
SoCraTes Days Linz 
JS CraftCamp 
CodeFreeze 
I T.A.K.E. Unconference

**Comment by arialdomartini** [comment]
Ok, quindi devo ripristinare la sezione che si chiamava Family?

**Comment by arialdomartini** [comment]
Ci sto lavorando.
Per ognuno dei partner nel tema originale viene riportato il link del sito e quello di Twitter. Lascio questo formato?

**Comment by arialdomartini** [comment]
Ho trovato anche SoCraTes Chile, che come immagine di sfondo usa un filmato

http://www.socrates-conference.cl/

**Comment by arialdomartini** [comment]
Ok, messi tutti e 12.
C'è da capire cosa fare del testo prima dell'elenco. Nel dubbio l'ho lasciato identico

![screen shot 2019-02-09 at 23 54 23](https://user-images.githubusercontent.com/150719/52527269-1d67cf00-2cc6-11e9-9d85-4a2ce4d1a13a.png)

**Comment by annapiera** [comment]
> Ho trovato anche SoCraTes Chile, che come immagine di sfondo usa un filmato
> 
> http://www.socrates-conference.cl/

Non mi parte alcun video....

**Comment by annapiera** [comment]
> Ok, messi tutti e 12.
> C'è da capire cosa fare del testo prima dell'elenco. Nel dubbio l'ho lasciato identico
> 
> ![screen shot 2019-02-09 at 23 54 23](https://user-images.githubusercontent.com/150719/52527269-1d67cf00-2cc6-11e9-9d85-4a2ce4d1a13a.png)

Possiamo eliminare i link sito e twitter e inserire l'hyperlink solo sul nome? 
Rendere il tutto più piccolo, perchè la sezione family così com'è articolata è enorme.

Me la immaginavo più in stile belgio: 

![image](https://user-images.githubusercontent.com/47472672/52536604-03c59680-2d5d-11e9-92d5-e6740315cfe6.png)

**Comment by annapiera** [comment]
Eliminiamo totalmente il testo scritto sotto, Ari..

**Comment by arialdomartini** [comment]
Ho lasciato solo il nome delle altre conf come link. 
Non è venuto bellino come quello del Belgio. Sono cetrate e il colore non è lo stesso. Gli manca forse anche il contrasto che ha il sito belga, con Our in bianco e la successiva parola in bold.
Boh, non mi sembra fondamentale, ma non è bello quanto il loro.

**Comment by annapiera** [comment]
Se non si può dividere su due colonne diciamo che non muore nessuno :) 

Magari l’hyperlink verde? 
Perché quell’azzurro è proprio nuovo nel sito 🙈

L’unica cosa è che ho notato un neologismo “PARTENERS”

Se mi sistemi in “PARTNERS” chiudo la issue :)

**Comment by arialdomartini** [comment]
![screen shot 2019-02-11 at 22 23 16](https://user-images.githubusercontent.com/150719/52594367-a9573380-2e4b-11e9-8b7c-12f48521e621.png)

Quando stringi molto passa a 1 colonna. Forse devo ridurre la dimensione alla quale scatta il passaggio da 2 colonne a 1.

Typo Parteners => Partners corretta, grazie!!!!o

**Comment by arialdomartini** [comment]
Messi i link in verde.

**Comment by annapiera** [comment]
Da mobile si vede solo una colonna, ma va bene! :) Chiudo! 
Aleeeee! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by annapiera** [comment]
@arialdomartini il link di SoCraTes fr e SoCraTes Canarie sono errati.
https://socrates-fr.github.io
https://socracan.com 

Pardon!

**Comment by arialdomartini** [comment]
> Se non si può dividere su due colonne diciamo che non muore nessuno :)

Dovrei aver rimediato. Non so se su tutti i mobile ...
