### ISSUE TITLE
[MENU] 

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#22]
compariranno le tab:
ABOUT
SCHEDULE
SPONSOR
bottone "REGISTER NOW"

**Comment by arialdomartini** [comment]
Ok, in questo momento nel menu ci sono: 

* About
* Partners
* Sponsor
* Register now

Tolgo Partners e metto Schedule, lasciando il contenuto della one-page inalterato?

**Comment by annapiera** [comment]
Precisamente sì, Mr Martini! :)

**Comment by arialdomartini** [comment]
Feci.
