### ISSUE TITLE
Partner 

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#24]
@arialdomartini il link di SoCraTes fr e SoCraTes Canarie sono errati.
https://socrates-fr.github.io
https://socracan.com 

Pardon!

**Comment by arialdomartini** [comment]
Non ti scappa nulla. Bravona.
Corretto.

**Comment by annapiera** [comment]
Ti renderò la vita difficile 🙈

Perfetto! Chiudo! :)
