### ISSUE TITLE
[HEADER] cambiare data: May, 2nd-5th 2019

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#25]

**Comment by arialdomartini** [comment]
![deepinscreenshot_select-area_20190213194758](https://user-images.githubusercontent.com/150719/52735720-800fe200-2fc8-11e9-8079-ac9e4a54d0b2.png)
![deepinscreenshot_select-area_20190213194921](https://user-images.githubusercontent.com/150719/52735722-800fe200-2fc8-11e9-800f-4a962200764d.png)


Ho preferito la versione 2-5 April. Che ne pensi, @annapiera?
