### ISSUE TITLE
About / il testo nelle descrizioni non è più giustificato

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#26]

**Comment by arialdomartini** [comment]
Te l'ho detto che CSS è una merdaccia. Penso sia stata l'introduzione dello scheduling. 
Mo risolvo.

**Comment by arialdomartini** [comment]
I testi sono di nuovo allineati e il sottotitolo di About è di nuovo centrato.

**Comment by annapiera** [comment]
Perfetto : )
Chiudo!
