### ISSUE TITLE
Aggiungere un banner per la GDPR

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#27]
Caro Martini... ma inserire un banner di avviso per il trattamento dati con link alla privacy policy... si può fare?

**Comment by arialdomartini** [comment]
Possiamo. Scegli un banner che ti piace?

Dobbiamo anche chiedere conferma a Irene se ne abbiamo bisogno. Io leggo:

> Tutti i cookie che raccolgono informazioni sulla persona e sono in grado di identificare un individuo, sono soggetti alla normativa europea sul trattamento dei dati personali. 
> Se usi Google Analytics non anonimizzato (ovvero senza mascherare l’indirizzo IP) significa che tramite i cookie di Analytics presenti sul tuo sito web stai memorizzando l’IP dei tuoi visitatori.

Se anomizziamo Google Analytics ho l'impressione che non abbiamo l'obbligo del banner. Sempre che non tu voglia invece raccogliere i dati di profilazione. Ne parliamo a voce? E troviamo il modo di parlare anche a Irene?

**Comment by arialdomartini** [comment]
Comunque, intanto scegliamo un banner?

**Comment by annapiera** [comment]
Martedì cerco di parlare con lei per approfondire, ma il banner è comunque relativo alla privacy policy. 

Sui temi Hugo non vedo banner, domani ne parliamo.

**Comment by annapiera** [comment]
Che ne dici di usare questo? 
https://www.cookiebot.com/it/pricing/

**Comment by arialdomartini** [comment]
Non riesco a vederlo, diobonino...

**Comment by annapiera** [comment]
@arialdomartini  proprio quello generato da questo sito...

Tu e gli AdBlock rovinerete il mondo! T____T

Ne parliamo domani di questo!

**Comment by annapiera** [comment]
Non riesco a stare ferma, quindi ho creato il banner (credo).

<script id="Cookiebot" src="https://consent.cookiebot.com/uc.js" data-cbid="5ca5fcef-5e0b-4402-b98e-23ae7f4d089f" type="text/javascript" async></script>

Qui la guida per l'implementazione: https://www.cookiebot.com/it/help/

**Comment by annapiera** [comment]
Mi faccio un update da sola, non installarlo.

Domani ti faccio vedere l'anteprima e mi dici se ti quadra.

**Comment by annapiera** [comment]
Copia questo script sull'header html del modello del tuo sito web per abilitare il banner del consenso:

```
<script id="Cookiebot" src="https://consent.cookiebot.com/uc.js" data-cbid="5ca5fcef-5e0b-4402-b98e-23ae7f4d089f" type="text/javascript" async></script>
```

Inserisci questo script nell'html della sottopagina in cui desideri mostrare il contenuto completo dell'informativa sui cookie.
```
<script id="CookieDeclaration" src="https://consent.cookiebot.com/5ca5fcef-5e0b-4402-b98e-23ae7f4d089f/cd.js" type="text/javascript" async></script>
```

**Comment by annapiera** [comment]
Guide per installazione:
https://www.cookiebot.com/it/developer/ 
https://www.cookiebot.com/it/help/

**Comment by arialdomartini** [comment]
Habemus cookie banner.
