### ISSUE TITLE
La barra di navigazione ha dimensioni sbagliate su mobile

### ISSUE THREAD

**Issue by arialdomartini** [socrates-it-test/site-source#29]
Scrollando in basso la barra dovrebbe ridursi di dimensioni. Invece, aumenta.

**Comment by arialdomartini** [comment]
Fixed. Su mobile la barra di navigazione e il logo non dovrebbero cambiare dimensione.

**Comment by annapiera** [comment]
Non cambia neanche a me, chiudo :)
