### ISSUE TITLE
[TAB 3] ABOUT

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#3]

**Comment by annapiera** [comment]
Il box diventerà:

IT IS ABOUT (centrato, uppercase, nero)

[sotto i tre box con le icone, se puoi farle diventare verdi ok, altrimenti te le cerco su un altro sito
nota: il testo dei box deve essere giustificato]
PEOPLE
Everyone who is concerned with coding, testing, code quality and software craftsmanship.
Meet us if you want to share your knowledge, experience and expertise.
There is no agenda and there are no speakers before the event starts. 

ACTION
The event will be run as a non-profit, low-cost event. It will be much like a retreat.
We will be there for 48 hours to collaborate and share ideas in a self-organized Open Space. 
There will be hands-on coding sessions, sessions focused on discussion, interactive talks and lots more.

FUN
We will not only spend the days together but also the nights. And – believe it or not – programmers are a great company! There will be be lots of opportunities to spend your time. Starting with simple chilling over hiking and biking, playing games, hanging around, talking and laughing.

**Comment by arialdomartini** [comment]
Ok, testi modificati e icone fatte verdi.

Ho 3 domande.

1. il testo sotto About lo lascio inalterato?

This event is about the sustainable creation of useful software in a responsible way.

2. Con testo giustificato intendi allineato sia a sinistra che a destra?


Allineato a sinistra
![screen shot 2019-02-09 at 22 45 08](https://user-images.githubusercontent.com/150719/52526683-9feb9100-2cbc-11e9-8554-4dc8ab41e3b2.png)


Giustificato
![screen shot 2019-02-09 at 22 44 49](https://user-images.githubusercontent.com/150719/52526684-a0842780-2cbc-11e9-9fcd-93960b03e144.png)

Centrato
![screen shot 2019-02-09 at 22 45 20](https://user-images.githubusercontent.com/150719/52526682-9feb9100-2cbc-11e9-8080-67d444576765.png)


3. Nei tuoi testi ci sono dei ritorni a capo. Li tengo?

**Comment by arialdomartini** [comment]
(Lascia stare il testo sotto it is about negli screenshot sopra: è un errore che non sia sempre centrato)

**Comment by annapiera** [comment]
Risposte:
1. Ok, inalterato, ma centrato come nell'ultimo screen.
2. Giustificato, però il primo blocco modificalo così:

Everyone who is concerned with coding, testing, code quality and software craftsmanship.
There is no agenda and there are no speakers before the event starts. speakers before the event starts. Proposals are presented during the event itself in the mornings, and voted by the participants right after. 
Meet us if you want to share your knowledge, experience and expertise!

3. Il primo testo l'ho modificato con 1 solo ritorno a capo.
Il secondo puoi togliere l'ultimo ritorno a capo dopo "Open Space."?
Il terzo va bene così. : )

4. I titoloni diventano solo PEOPLE/ACTION/FUN senza "It's" che è decisamente bruttarello. Puoi cambiarlo?

**Comment by arialdomartini** [comment]
Fatto.

**Comment by annapiera** [comment]
Non vedo cambiamenti e vado anche in incognito... 🙄

**Comment by arialdomartini** [comment]
sto aggiornando adesso.

**Comment by annapiera** [comment]
Arialdo, non ti rompo tanto se elimini tutti gli a capo del primo e secondo riquadro?

Poi è perfetto!

**Comment by arialdomartini** [comment]
Fatto e pubblicato

**Comment by annapiera** [comment]
Perfetto! 😁 Chiudo! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
