### ISSUE TITLE
Logo nel Menu - pagina registration non compare 

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#30]
Da mobile, da desktop non saprei

**Comment by arialdomartini** [comment]
Possibile duplicato di #31 ?

**Comment by annapiera** [comment]
Nope, mi spiego meglio.

Quando sono sulla pagina della registrazione il logo del SoCraTes nel menu in alto non si vede.

**Comment by annapiera** [comment]
Sì, è un duplicato...
Ora noto che è sparito del tutto.
