### ISSUE TITLE
Menu a tendina - mobile / bug

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#31]
Da mobile il menu a tendina del sito non compare più...

**Comment by arialdomartini** [comment]
Ok, ho visto. Il problema è stato introdotto con i CSS dello scheduling.
Ho risolto, ma vedo altri 3 problemi (che segno a parte):

* il CTA nel menu a tendina su mobile è orrido
* lo scheduling su Mobile è impaginato proprio male
* ho dovuto togliere il logo: in locale mi dava problemi. Lo riaggiungo da ultimo.

**Comment by annapiera** [comment]
Si, il bottone per la registrazione non è molto carino da mobile.

Si può eliminare il rosso intorno? Ma solo da mobile, non so se sia possibile...

**Comment by arialdomartini** [comment]
Sì sì, è possibile.
Ho ridotto la dimensione del pulsante.
Guarda un po' se va bene così. Se vuoi, tolgo comunque il rosso, è un attimo.

**Comment by annapiera** [comment]
Sisi, togliamo il bordo.

Lasciamo scritta "register now" in rosso, non staccato.

**Comment by arialdomartini** [comment]
Done

**Comment by annapiera** [comment]
Perfetto! :)
