### ISSUE TITLE
Nelle pagine secondarie manca il footer

### ISSUE THREAD

**Issue by arialdomartini** [socrates-it-test/site-source#40]
Per esempio, in Register now.

**Comment by arialdomartini** [comment]
Aggiunto

**Comment by arialdomartini** [comment]
@annapiera io in generale quando ho finito una issue la assegno a te così puoi dare un secondo controllo e se qualcosa non ti piace puoi segnalarmelo. Insomma, le issue le faccio chiudere a te per double check. Ok?

**Comment by annapiera** [comment]
Yeppaaaa :) 
Ottimo metodo!
