### ISSUE TITLE
Mettere il logo di Connexxo tra gli sponsor

### ISSUE THREAD

**Issue by arialdomartini** [socrates-it-test/site-source#43]
![0](https://user-images.githubusercontent.com/150719/53427182-beee6080-39e8-11e9-8d96-24a2df3bd48e.png)

**Comment by arialdomartini** [comment]
@annapiera c'è da capire meglio come sistemare questa sezione. Adesso è pensata per chiedere l'adesione alla sponsorship, non per elencare gl sponsor.
Come deve intotorarsi? Sporsos? O Sponsorship? Inizia con gli (lo) sponsor? O con la richiesta a diventare sponsor? Il sottotitolo è "Do you want to sponsor the event" ma sotto inizia l'elenco degli sponsor....

**Comment by annapiera** [comment]
![sponsor](https://user-images.githubusercontent.com/47472672/53442620-03d6bf00-3a0a-11e9-812f-6bd514c7ddec.png)
Ti ho fatto il disegnino, in pratica:
- spostiamo "it would be..." sotto
- in mezzo inseriamo il logo di connexxo 
- prevediamo di poter inserire altri sponsor a destra e sinistra di connexo.

Ci sta? 

Comunque, titolone "sponsors", non so come mi sia venuto sponsorship....

**Comment by annapiera** [comment]
Questions?

**Comment by arialdomartini** [comment]
Fatto!
