### ISSUE TITLE
Cookie policy 

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#44]
@arialdomartini prevedere nel mentre un'altra pagina tipo cookie policy linkata nel footer

Thank youuuu!

**Comment by annapiera** [comment]
[Cookie Policy - SoCraTes IT.docx](https://github.com/socrates-it-test/site-source/files/2907372/Cookie.Policy.-.SoCraTes.IT.docx)
Pronta!

**Comment by arialdomartini** [comment]
Done!
Grazie, @annapiera.
