### ISSUE TITLE
Registration > modificare testo

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#45]
Al posto di: https://socrates-it-test.github.io/registration/
2 nights full-board + the city tax:
**the hotel has both twin or double rooms. If** there is someone you are willing to share the room with, please let us know when you register. If you don’t know anyone, don’t worry: we will do our best to find you a suitable roommate ;-)  

**the hotel has both single or double rooms.**

**Comment by arialdomartini** [comment]
Fatto. Ho tolto il ;-)  però, ti rompe? Secondo me se siamo seri al momento della registrazione non guasta.

**Comment by annapiera** [comment]
Va benissimo!
