### ISSUE TITLE
Anominizzare IP GA

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#46]
https://www.iubenda.com/it/help/943-come-anonimizzare-gli-ip-ed-evitare-la-condivisione-dei-dati-in-google-analytics

L'IP si può anonimizzare così

**Comment by arialdomartini** [comment]
Done!

**Comment by arialdomartini** [comment]
In generale, adesso, per verificare che le cose funzionino a modino dobbiamo aspettare che Gabriele metta il sito in produzione. Alcune cose funzioneranno anche da socrates-test-it.github.io (credo per esempio che Google Analytics veda i due siti come uno solo, perché il codice è lo stesso)...

Tengo le issue aperte per ricordarci di fare una verifica che tutto funzioni come deve.

**Comment by annapiera** [comment]
yap, ok!
