### ISSUE TITLE
Inserire codice User ID

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#47]
Ti ho inviato per e-mail i dettagli

**Comment by arialdomartini** [comment]
@annapiera mi dovresti mandare il codice dello UserID che vedi nel pannello di Google Analyrics. Nella mail che mi hai spedito c'è l'esempio di codice, ma manca l'ID del tuo account.

Ho inserito nel codice 
```
 gtag('set', {'user_id': 'USER_ID'});
```
come da tua email, ma ho l'impressione che al posto di `USER_ID` si debba mettere lo user id che ti viene mostrato nel pannello di Google Analytics.

**Comment by arialdomartini** [comment]
Forse no. Dovrebbe bastare scrivere `USER_ID`, da quel che leggo in https://developers.google.com/analytics/devguides/collection/gtagjs/cookies-user-id

**Comment by annapiera** [comment]
Anche da ciò che vedo io....
https://support.google.com/analytics/answer/3123666?hl=it&authuser=2&ref_topic=3123660 
Ho bisogno di più dati per vedere se funge...
