### ISSUE TITLE
Il sito non è Https > non sicuro

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#48]
Come si risolve la cosa?

**Comment by arialdomartini** [comment]
Ho aperto una issue a Gabriele https://github.com/socrates-it/socrates-it.github.io/issues/3

**Comment by annapiera** [comment]
BravaaaHHH

**Comment by annapiera** [comment]
@arialdomartini Il sito non è ancora sicuro.

![image](https://user-images.githubusercontent.com/47472672/74506626-6c100080-4efa-11ea-9e1e-3ba47ce6c711.png)

**Comment by arialdomartini** [comment]
Per dettaglio: https://www.socrates-conference.it/ funziona correttamente, ma risponde anche a http.

**Comment by VenomAV** [comment]
Ho forzato il redirect a https, ora se nel browser mettete http://socrates-conference.it vi rimanda a https://
