### ISSUE TITLE
Ridurre Mappa di Google

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#49]
Solo se è facilino!

**Comment by arialdomartini** [comment]
è facilissimo. 
Devo solo cambiare qui:

```
 width="100%" height="750"
```

Dimmi come lo vuoi. Il problema è su Mobile? O in generale? Quanto la vuoi grande?

**Comment by annapiera** [comment]
Ti trovo un sito di esempio così è più chiaro :)

**Comment by annapiera** [comment]
![mappa](https://user-images.githubusercontent.com/47472672/53681931-a5069380-3cf0-11e9-942f-9cf29bf1d90f.png)
Tipo così? (vedi riquadro disegnato)

**Comment by arialdomartini** [comment]
Done
