### ISSUE TITLE
[TAB 4] SCHEDULE Inserire schedule per timeline giornate

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#5]

**Comment by annapiera** [comment]
Inserire dashboard interattiva dove inserire le agende delle tre giornate (come sul sito belga), se non è possibile cerchiamo un'alternativa

**Comment by annapiera** [comment]
Aggiungo, se non riusciamo ho trovato queste due che sembrano comunque ordinate:
![image](https://user-images.githubusercontent.com/47472672/52536502-b137aa80-2d5b-11e9-8347-bcfeb3a13d2d.png)
http://jscraftcamp.org/ 
![image](https://user-images.githubusercontent.com/47472672/52536506-c1e82080-2d5b-11e9-8062-0be696f33fb2.png)
https://socracan.com/

**Comment by arialdomartini** [comment]
- adesso è su 3 giorni, non 4
- ho messo le date giuste
- ho tolto i riferimenti a SoCraTes BE
- ho cambiato i colori da ariancione a verde


Se vuoi editare i contenuti, puoi modificare questo file

https://github.com/socrates-it-test/site-source/blob/master/themes/hugo-agency-theme/layouts/partials/schedule.html

Siccome è HTML, magari non ti trovi bene a modificarlo. Se preferisci passarmi i testi invece di modificarlo tu eccomi qui al suo servigio!

**Comment by annapiera** [comment]
@arialdomartini manca il titolone "SCHEDULE" ed il collegamento nel menu

Invio un'e-mail per chiedere quale sarà l'agenda

**Comment by arialdomartini** [comment]
Questa l'agenda dello scorso anno

    giovedì
        dalle 15.00 arrivo partecipanti, birre e networking
        19.30 cena presso hotel
        21:00 attività serali (avevamo fatto un world coffee e un gioco per mettere tutti nel mood giusto)
    venerdì
        9:00 - opening the space (spiegazione funzionamento unconference con regola e principi) e definizione agenda della giornata
        10:00 - 13:00 sessioni 
        13:00 - 14:30 pranzo
        14:30 - 17:30 sessioni
        17:30 - evening news (recap della giornata e condivisione)
        19:30 - cena
        21:00 - 23:00 e oltre - attività serali
    sabato
        9:00 - opening the space (spiegazione funzionamento unconference con regola e principi) e definizione agenda della giornata
        10:00 - 13:00 sessioni 
        13:00 - 14:00 pranzo
        14:00 - 16:00 sessioni
        16:00 - 17:00 closing the space
        17:00 in poi - ritorno partecipanti

Traduco e modifico la pagina? Vuoi pensarci tu?

**Comment by arialdomartini** [comment]
> @arialdomartini manca il titolone "SCHEDULE" ed il collegamento nel menu
Messo.
Adesso risolvo il problema delle 3 colonne

**Comment by annapiera** [comment]
Ci penso me, domani :)

**Comment by annapiera** [comment]
**Thursday**

3:00 p.m. - Welcome in! 
We kick off SoCraTes IT 2019 with a good beer and networking activities

7:30 p.m. - Dinner time
We have a good dinner all together 

9:00 p.m. - After-dinner
We do a team-building game to know each other

**Friday**


08:00 a.m. - Wake up, lazy guys! 
Time to have a breakfast 

9:00 a.m. - Official opening 
Introduction of Cecilia about the spirit of SoCraTes IT and the Open Space

9:30 a.m. - Marketplace
Time for everyone to write down their sessions and pick a slot on the market place

10:00 a.m. - Sessions
3 hours session 

1:00 p.m. - Lunch
Time to refuel 

2:30 p.m. - Sessions 
3 hours session 

5:30 p.m. - Evening news 
Time to recap all day and share your impression

7:30 p.m. - Dinner 
Time to give energy to your brain

9:00 p.m. - Before closing your eyes...
The floor is yours to continue the conversation, twist it around and branch it in every direction

**Sunday**

8:00 a.m. - The early bird gets the worm
Time to have a breakfast 

9:00 a.m. - Marketplace 
Time for everyone to write down their sessions and pick a slot on the market place.

10:00 a.m. - Sessions
3 hours session 

1:00 p.m. - Lunch 
Time to refuel 

2:00 p.m. - Sessions 
2 hours session 

4:00 p.m. - Official Closing 
We recap all the days and share our impression

5:00 - It is time to say Goodbye!
Time flies when you're having fun

**Comment by arialdomartini** [comment]
Fatto.
Ho solo sostituito "3 hours sessions" con "1-hour sessions": non si capiva se significasse "sessioni da 3 ore"

**Comment by arialdomartini** [comment]
Il primo giorno le sessioni iniziano alle 2:30, il secondo alle 2. Un errore?

**Comment by annapiera** [comment]
@arialdomartini 

> Il primo giorno le sessioni iniziano alle 2:30, il secondo alle 2. Un errore?

Me lo sono chiesta anche io, è giusto perchè finisce prima...

**Comment by annapiera** [comment]
Comunque: @arialdomartini è normale che io veda i titoletti schiacciati?

![image](https://user-images.githubusercontent.com/47472672/53444140-a7759e80-3a0d-11e9-88eb-af8cec237570.png)

**Comment by arialdomartini** [comment]
Uhm... No...
Però, se mi parli con in congiuntivi io mi sciolgo e non capisco più nulla...
Ci guardo.

**Comment by annapiera** [comment]
Va bene così : )
