### ISSUE TITLE
Cambiare cookie banner > non funziona più

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#50]
Gruppo di dominio ID: 5ca5fcef-5e0b-4402-b98e-23ae7f4d089f 
Chiave API: Mostra - Rinnova
Copia questo script sull'header html del modello del tuo sito web per abilitare il banner del consenso:

```
<script id="Cookiebot" src="https://consent.cookiebot.com/uc.js" data-cbid="5ca5fcef-5e0b-4402-b98e-23ae7f4d089f" type="text/javascript" async></script>
```

Inserisci questo script nell'html della sottopagina in cui desideri mostrare il contenuto completo dell'informativa sui cookie. >> Cookie policy page

```
<script id="CookieDeclaration" src="https://consent.cookiebot.com/5ca5fcef-5e0b-4402-b98e-23ae7f4d089f/cd.js" type="text/javascript" async></script>
``

Per l'implementazione, ti rimandiamo alla nostra guida all'installazione in 3 fasi, alla nostra guida per gli sviluppatori, e alla nostra area di supporto (in inglese)


Come sai è un copy-paste.

**Comment by arialdomartini** [comment]
Ti do una bella notizia.
Il codice non cambia. Prima era

```
<script id="Cookiebot" 
  src="https://consent.cookiebot.com/uc.js" 
  data-cbid="5ca5fcef-5e0b-4402-b98e-23ae7f4d089f" 
  type="text/javascript" async></script>
```

adesso è:

```
<script id="Cookiebot" 
  src="https://consent.cookiebot.com/uc.js" 
  data-cbid="5ca5fcef-5e0b-4402-b98e-23ae7f4d089f" 
  type="text/javascript" async></script>
```

Mi sembra proprio identico.

**Comment by arialdomartini** [comment]
In sostanza: avendo cambiato le impostazioni su Cookiebot hai risolto il problema. Il codice di riferimento di quella configurazione non è cambiato, per cui significa che puoi liberamente riconfigurare il banner dal sito senza bisogno di fare nuovi deployment.

**Comment by annapiera** [comment]
Questa è una notizia che mi rende tanto felice! 😍
