### ISSUE TITLE
Modificare PP

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#51]

**Comment by arialdomartini** [comment]
Sono cose tue, vero? Perché non so cosa sia il PP... La mail di risposta?

**Comment by annapiera** [comment]
Sî, devo modificare la Privacy Policy con quelle cose di google per gmail e oltretutto credo dovrei inserire qualcosa su google maps

**Comment by annapiera** [comment]
[Privacy policy - Socrates IT 2019.docx](https://github.com/socrates-it-test/site-source/files/2922473/Privacy.policy.-.Socrates.IT.2019.docx)
Ellallllà.

Ho modificato la privacy policy inserendo mailchimp, bitly, gmail.
Corretto qualche orrore ortografico.

La potresti ricaricare? : ))

**Comment by arialdomartini** [comment]
done.
