### ISSUE TITLE
Ricreare banner mailchimp

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#52]
pre-registration >>> register definitivo

**Comment by arialdomartini** [comment]
done.

**Comment by arialdomartini** [comment]
Cioè: dove nel testo della pagina di registrazione si parlava di pre-registrarsi, ho messo registrarsi.
Ho anche spostato il form di registrazione in alto, e l'ho messo in un riquadro.

**Comment by annapiera** [comment]
Va benissimo! 
Ho visto però che hai messo uno sfondo grigino un po' particolarino.
Riusciamo ad inserire un colore chiaro tipo un giallino o verdino o lasciarlo bianco (con il bordo verde)?
Sfondo bianco e bordo verde sarebbe carino.

Complicatino inutilino?

**Comment by annapiera** [comment]
Arialdo, lo so che mi odierai. Ma relativamente al testo del form della registrazione...
Potresti modificarlo coattamente?

Questa parte:
```
You can unsubscribe at any time by clicking the link in the footer of our emails. In compliance with art.6, 12 and 13 of GDPR – General Data Protection Regulation, Reg. UE 679/2016 I declare to have read and understood SoCraTes IT’s privacy policy.

We use Mailchimp as our marketing platform. By clicking below to subscribe, you acknowledge that your information will be transferred to Mailchimp for processing. Learn more about Mailchimp's privacy practices here.
```

Può diventare semplicemente come segue?  
I declare to have read and understood SoCraTes IT’s Privacy Policy

Con hyperlink su PP : http://www.socrates-conference.it/privacy-policy/

Ho aggiornato tutta la PP, anche i riferimenti a mailchimp, quindi è inutile avere così tanto testo nel form. Diventerebbe più snello!

**Comment by annapiera** [comment]
Inoltre, modificare quanto segue:

Da:
[bold]GDPR Permissions
[descr.]Please select all the ways you would like to hear from SoCraTes IT:
[SPUNTA]Email

A: 
[descr.] I wish to receive email communications from SoCraTes IT, including news about our conferences.
[spunta] YES

**Comment by annapiera** [comment]
E lo so. Non mi vorrai più vedere, ma ora ci servono oltre all'e-mail, anche nome e cognome.

Quindi il form base è questo:


<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<style type="text/css">
	#mc-embedded-subscribe-form input[type=checkbox]{display: inline; width: auto;margin-right: 10px;}
	#mergeRow-gdpr {margin-top: 20px;}
	#mergeRow-gdpr fieldset label {font-weight: normal;}
	#mc-embedded-subscribe-form .mc_fieldset{border:none;min-height: 0px;padding-bottom:0px;}
</style>
<div id="mc_embed_signup">
<form action="https://socrates-conference.us20.list-manage.com/subscribe/post?u=4e24ba7602f7acf9fe79737d3&amp;id=be9dbd9e7a" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>Secure your seat for SoCraTes IT and register here!</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
	<label for="mce-FNAME">First Name  <span class="asterisk">*</span>
</label>
	<input type="text" value="" name="FNAME" class="required" id="mce-FNAME">
</div>
<div class="mc-field-group">
	<label for="mce-LNAME">Last Name  <span class="asterisk">*</span>
</label>
	<input type="text" value="" name="LNAME" class="required" id="mce-LNAME">
</div>
<div id="mergeRow-gdpr" class="mergeRow gdpr-mergeRow content__gdprBlock mc-field-group">
    <div class="content__gdpr">
        <label>GDPR Permissions</label>
        <p>Please select all the ways you would like to hear from SoCraTes IT:</p>
        <fieldset class="mc_fieldset gdprRequired mc-field-group" name="interestgroup_field">
		<label class="checkbox subfield" for="gdpr_11381"><input type="checkbox" id="gdpr_11381" name="gdpr[11381]" value="Y" class="av-checkbox gdpr"><span>Email</span> </label>
        </fieldset>
        <p>You can unsubscribe at any time by clicking the link in the footer of our emails. 
In compliance with art.6, 12 and 13 of GDPR – General Data Protection Regulation, Reg. UE 679/2016  I declare to have read and understood SoCraTes IT’s privacy policy.</p>
    </div>
    <div class="content__gdprLegal">
        <p>We use Mailchimp as our marketing platform. By clicking below to subscribe, you acknowledge that your information will be transferred to Mailchimp for processing. <a href="https://mailchimp.com/legal/" target="_blank">Learn more about Mailchimp's privacy practices here.</a></p>
    </div>
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_4e24ba7602f7acf9fe79737d3_be9dbd9e7a" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[4]='PHONE';ftypes[4]='phone';fnames[5]='BIRTHDAY';ftypes[5]='birthday';}(jQuery));var $mcj = jQuery.noConflict(true);</script>

**Comment by annapiera** [comment]
Ovviamente questo pippone è da modificare come quanto inteso sopra...
Perdonami. : /

**Comment by annapiera** [comment]
Il nuovo form deve richiedere anche nome e cognome...
Quindi questa è la nuova base da cui partire...


<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<style type="text/css">
	#mc-embedded-subscribe-form input[type=checkbox]{display: inline; width: auto;margin-right: 10px;}
	#mergeRow-gdpr {margin-top: 20px;}
	#mergeRow-gdpr fieldset label {font-weight: normal;}
	#mc-embedded-subscribe-form .mc_fieldset{border:none;min-height: 0px;padding-bottom:0px;}
</style>
<div id="mc_embed_signup">
<form action="https://socrates-conference.us20.list-manage.com/subscribe/post?u=4e24ba7602f7acf9fe79737d3&amp;id=be9dbd9e7a" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>Secure your seat for SoCraTes IT and register here!</h2>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address </label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
	<label for="mce-FNAME">First Name </label>
	<input type="text" value="" name="FNAME" class="required" id="mce-FNAME">
</div>
<div class="mc-field-group">
	<label for="mce-LNAME">Last Name </label>
	<input type="text" value="" name="LNAME" class="required" id="mce-LNAME">
</div>
<div id="mergeRow-gdpr" class="mergeRow gdpr-mergeRow content__gdprBlock mc-field-group">
    <div class="content__gdpr">
        <label>Permissions</label>
        <p>I wish to receive email communications from SoCraTes IT, including news about our conferences.
</p>
        <fieldset class="mc_fieldset gdprRequired mc-field-group" name="interestgroup_field">
		<label class="checkbox subfield" for="gdpr_11381"><input type="checkbox" id="gdpr_11381" name="gdpr[11381]" value="Y" class="av-checkbox gdpr"><span>Yes</span> </label>
        </fieldset>
        <p>I declare to have read and understood SoCraTes IT’s Privacy Policy.</p>
    </div>
    <div class="content__gdprLegal">
        <p>We use Mailchimp as our marketing platform. By clicking below to subscribe, you acknowledge that your information will be transferred to Mailchimp for processing. <a href="https://mailchimp.com/legal/" target="_blank">Learn more about Mailchimp's privacy practices here.</a></p>
    </div>
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_4e24ba7602f7acf9fe79737d3_be9dbd9e7a" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>

**Comment by arialdomartini** [comment]
> Riusciamo ad inserire un colore chiaro tipo un giallino o verdino o lasciarlo bianco (con il bordo verde)?
> Sfondo bianco e bordo verde sarebbe carino.
> Complicatino inutilino?

No, certo, facilissimo. Anche a me non convinceva quel grigio. Triste. Mo ci lavoro.

**Comment by arialdomartini** [comment]
Tu sceglie....

# 1
 ![1](https://user-images.githubusercontent.com/150719/53692247-b1d8c500-3d8c-11e9-9c65-e6dec5865a72.png)

# 2
 ![2](https://user-images.githubusercontent.com/150719/53692250-b56c4c00-3d8c-11e9-979f-078a47a8d780.png)

#3 
 ![3](https://user-images.githubusercontent.com/150719/53692252-b7360f80-3d8c-11e9-85fd-2d90ee52a7be.png)

#4 
 ![4](https://user-images.githubusercontent.com/150719/53692254-b9986980-3d8c-11e9-81cf-0129b127ce15.png)

#5
![5](https://user-images.githubusercontent.com/150719/53692255-bbfac380-3d8c-11e9-97c0-50984a199237.png)

**Comment by arialdomartini** [comment]
> Arialdo, lo so che mi odierai. Ma relativamente al testo del form della registrazione...
> Potresti modificarlo coattamente?
> 
> Questa parte:
> 
> ```
> You can unsubscribe at any time by clicking the link in the footer of our emails. In compliance with art.6, 12 and 13 of GDPR – General Data Protection Regulation, Reg. UE 679/2016 I declare to have read and understood SoCraTes IT’s privacy policy.
> 
> We use Mailchimp as our marketing platform. By clicking below to subscribe, you acknowledge that your information will be transferred to Mailchimp for processing. Learn more about Mailchimp's privacy practices here.

Fatto

**Comment by arialdomartini** [comment]
Per adesso ho pubblicato il layout 2.

**Comment by annapiera** [comment]
Non riesco a vedere l’anteprima sul sito, emh. 
Comunque nell’ultimo messaggio/codice che ho inviato c’era anche la predisposizione per l’inserimento di none e cognome. 
Non so se tu l’abbia fatto. Emh. 

Layout 2 mi piace molto! :D

**Comment by annapiera** [comment]
Il nuovo form deve richiedere anche nome e cognome...
Quindi questa è la nuova base da cui partire...

```
<!-- Begin Mailchimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<style type="text/css">
	#mc-embedded-subscribe-form input[type=checkbox]{display: inline; width: auto;margin-right: 10px;}
	#mergeRow-gdpr {margin-top: 20px;}
	#mergeRow-gdpr fieldset label {font-weight: normal;}
	#mc-embedded-subscribe-form .mc_fieldset{border:none;min-height: 0px;padding-bottom:0px;}
</style>
<div id="mc_embed_signup">
<form action="https://socrates-conference.us20.list-manage.com/subscribe/post?u=4e24ba7602f7acf9fe79737d3&amp;id=be9dbd9e7a" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>Secure your seat for SoCraTes IT and register here!</h2>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address </label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
	<label for="mce-FNAME">First Name </label>
	<input type="text" value="" name="FNAME" class="required" id="mce-FNAME">
</div>
<div class="mc-field-group">
	<label for="mce-LNAME">Last Name </label>
	<input type="text" value="" name="LNAME" class="required" id="mce-LNAME">
</div>
<div id="mergeRow-gdpr" class="mergeRow gdpr-mergeRow content__gdprBlock mc-field-group">
    <div class="content__gdpr">
        <label>Permissions</label>
        <p>I wish to receive email communications from SoCraTes IT, including news about our conferences.
</p>
        <fieldset class="mc_fieldset gdprRequired mc-field-group" name="interestgroup_field">
		<label class="checkbox subfield" for="gdpr_11381"><input type="checkbox" id="gdpr_11381" name="gdpr[11381]" value="Y" class="av-checkbox gdpr"><span>Yes</span> </label>
        </fieldset>
        <p>I declare to have read and understood SoCraTes IT’s Privacy Policy.</p>
    </div>
    <div class="content__gdprLegal">
        <p>We use Mailchimp as our marketing platform. By clicking below to subscribe, you acknowledge that your information will be transferred to Mailchimp for processing. <a href="https://mailchimp.com/legal/" target="_blank">Learn more about Mailchimp's privacy practices here.</a></p>
    </div>
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_4e24ba7602f7acf9fe79737d3_be9dbd9e7a" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
<!--End mc_embed_signup-->
