### ISSUE TITLE
Button in confirmation email has the wrong background when the mouse is hover

### ISSUE THREAD

**Issue by arialdomartini** [socrates-it-test/site-source#58]
![image](https://user-images.githubusercontent.com/150719/53806348-05920c80-3f4d-11e9-8772-2c04c4a5392c.png)

è qualcosa che va sistemato su MailChimp, penso. Se vuoi, @annapiera, ci guardiamo insieme.

**Comment by annapiera** [comment]
![image](https://user-images.githubusercontent.com/47472672/53806574-97017e80-3f4d-11e9-94e1-02d8c97aaa04.png)
a me esce così arialdo...
stai usando firefox?
