### ISSUE TITLE
Pulsante nella pagina di registrazione finale

### ISSUE THREAD

**Issue by arialdomartini** [socrates-it-test/site-source#59]
![image](https://user-images.githubusercontent.com/150719/53806487-66b9e000-3f4d-11e9-9246-d64830e3ef9c.png)

Per consistenza con il sito, metterei il pulsante verde.

**Comment by arialdomartini** [comment]
Leonardo ha trovato questa soluzione:

```
.msg4729837841803612324 .m_4729837841803612324formEmailButton{
 background-color:#5d5d5d;
 color:#ffffff;
}
.msg4729837841803612324 .m_4729837841803612324formEmailButton:hover {
 background-color:red!important;
 color:#ffffff!important;
}
```

**Comment by annapiera** [comment]
Oddio, Arialdo c'è la possibilità di creare il codice dell'e-mail, ma io
non so metterci mani...


*Anna Piera Frascella*


Il giorno mer 6 mar 2019 alle ore 09:08 Arialdo Martini <
notifications@github.com> ha scritto:
