### ISSUE TITLE
[TAB 6] Cambiare box information

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#6]

**Comment by annapiera** [comment]
#6

Eliminare scritte "information"
Cambiare le tre tab, diventeranno:

VALUES
OPEN SPACE
CODE OF CONDUCT

Nota: nel formato originale il titolo della tab viene replicato, non so perchè, eliminare la duplicazione

**Comment by annapiera** [comment]
Immagini di anteprima per le tab:

VALUES: http://bit.ly/2Dne0xz 
OPEN SPACE: http://bit.ly/2tf5n3C
CODE OF CONDUCT: http://bit.ly/2Buw4ph  

Questo set di icone mi sembra molto carino per tutto il sito: http://bit.ly/2MWiWOe

**Comment by arialdomartini** [comment]
Ah ah ah, rickrollato!!!!

**Comment by arialdomartini** [comment]
Non ho capito nulla, aiuto. Non ho capito cosa siano le tab, i titoli duplicati, dove dovrei mettere quelle immagini... Aiuto...

**Comment by arialdomartini** [comment]
Ah, penso di aver capito: i tab sono le varie sezioni, associate ai pulsanti nella navigation bar.
Quando hai modo mi spieghi come funzionano le immagini di anteprima, dove vuoi visualizzarle. Anche domani. Io sono tutto il giorno fuori: se riesco lavoro al sito un po' stasera.

**Comment by annapiera** [comment]
Domani parliamo di questo : )
No problem!

**Comment by annapiera** [comment]
va unito con about, vedi #3

**Comment by arialdomartini** [comment]
![screen shot 2019-02-11 at 21 26 07](https://user-images.githubusercontent.com/150719/52591377-22528d00-2e44-11e9-9b60-248b9aeb0cdb.png)

![screen shot 2019-02-11 at 21 29 07](https://user-images.githubusercontent.com/150719/52591375-22528d00-2e44-11e9-8084-f3da4b6bc604.png)

**Comment by annapiera** [comment]
Non ti convince, vero?

**Comment by annapiera** [comment]
Centrati, magari...

**Comment by arialdomartini** [comment]
Mica tanto... Delle foto fanno più allegria. Non saprei quali, però.

**Comment by annapiera** [comment]
Domani te le trovo io :)
-- 
Anna Piera Frascella

**Comment by annapiera** [comment]
Qui le foto:
VALUES: https://pixabay.com/it/azione-collaborare-collaborazione-2277292/ 
OPEN SPACE: https://pixabay.com/it/lavagna-bianca-uomo-presentazione-849812/ 
CODE OF CONDUCT: https://pixabay.com/it/mano-rubik-cubo-puzzle-gioco-2208491/ 

Che ne dici? 
Ora ti mando i testi.

**Comment by annapiera** [comment]
[BOX _ VALUES - CODE - OPEN SPACE.docx](https://github.com/socrates-it-test/site-source/files/2871991/BOX._.VALUES.-.CODE.-.OPEN.SPACE.docx)
Qui trovi tutti i testi : )

**Comment by arialdomartini** [comment]
Ho messo immagini e testi.

* Ho aggiunto il link al Code of Conduct di Django che citavi
* HO TOLTO TUTTI I MAIUSCOLI DA DAGOSPIA, NON SI POSSONO VEDERE!!!!111!!!

**Comment by arialdomartini** [comment]
Ah un dubbio. Nel testo di Our Value parli del Code Of Conduct:

> This code of conduct applies to the SoCraTes conference itself and to all digital spaces that are related to the SoCraTes conference, such as the wiki and mailing list.

Giusto così?

**Comment by annapiera** [comment]
Hai ragione arialdo, quel pezzo andrebbe alla fine di “code of conduct”. In “values” non calza.

Ho notato un altro errore in Open Space:
“SoCraTes IT will be run as a three day Open Space”
Diventa:
“SoCraTes IT will be run as a three days Open Space”
Mancava la S. 

Poi c’è un altro problemino, quando apri una delle tre box sotto c’è scritto “close”, quando clicchi su close diventa giallo.

**Comment by arialdomartini** [comment]
Corretto tutto.

**Comment by annapiera** [comment]
Wait.

In code of conduct (full version) e open space (open space e Pierluigi) sono spariti gli hyperlink!

**Comment by arialdomartini** [comment]
Ho messo il link a Connexxo e ho cambiato il nome del coach da Pierluigi a Cecilia.

**Comment by arialdomartini** [comment]
Invece, in Values il link a Django Code of Conduct funzionava già.

**Comment by annapiera** [comment]
Update.

Mancano ancora due link:
- code of conduct su “full version”
- open space su “open space”.

**Comment by arialdomartini** [comment]
Sei una macchina umana.
Corretto e pubblicato.
