### ISSUE TITLE
Agile Crete 2020

### ISSUE THREAD

**Issue by arialdomartini** [socrates-it-test/site-source#65]
Agile Crete 2020 is going to be held again at Kolymbari, Crete, at May 20th - 23rd. 
The references in SoCraTes should be accordingly updated.

**Comment by annapiera** [comment]
Nella home/partners aggiungere 

[Agile Crete](https://agilecrete.org/)

**Comment by arialdomartini** [comment]
Done. @nvoulgaris, this will be online in the very next days. Thank you!

**Comment by arialdomartini** [comment]
Hi @nvoulgaris, we included a link to the Agile Crete in our site. 
I have just noticed this year you will meet SoCraTes. That's a great news!

I wonder if it makes sense we promote your 2020 edition via Twitter with the @SoCraTes_Italy account. It would be a great pleasure for us!
