### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#67]
Cambiamenti pagina registrazione: http://www.socrates-conference.it/registration/ 

**Location:**
We are going to be in the hotel, night and day. That is why we have chosen the [AlpHoliday Dolomiti Wellness & Fun Hotel](https://www.alpholiday.it/) in Dimaro (TN) as our location for the unconference.

Since one of the important aspects of SoCraTes is being close to the “action”, everything will happen within the location: lodging, eating and mingling. As a result, we can only accept as many participants as the number of available beds.

**Google Maps:**
lo trovi facilmente:
Hotel AlpHoliday Dolomiti
Via Campiglio, 4, 38025 Dimaro TN

Codice:
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2755.0953848831678!2d10.869012615586582!3d46.327800479120626!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4782f59f0efeb1bf%3A0xee0d0102dd67f101!2sHotel%20AlpHoliday%20Dolomiti!5e0!3m2!1sen!2sch!4v1582100329275!5m2!1sen!2sch" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>

**Comment by annapiera** [comment]
**TESTO EDITATO 19-02-2020** 

**What is it included in the cost?**

- Two nights full-board: breakfast, lunch, dinner and snack buffet all day (vegetarian and gluten-free food included!)
The hotel has both twin or double rooms. If there is someone you are willing to share the room with, feel free to book the double room. If you don’t know anyone, don’t worry: sign in the [Sofware Crafters #italian channel on Slack](http://slack.softwarecraftsmanship.org/) and find a suitable roommate.
- City tax
- Access to the wellness area: indoor pool, heated outdoor pool, and wet area
-  Access to the gym with cardio and fitness equipment
- _[Guest card Trentino](https://www.visittrentino.info/en/experience/trentino-guest-card)_: free circulation on public transport within Trentino and free or discounted entry to over 60 museums, 20 castles, and 20 attractions.
- Use of mountain bikes

The unconference’s beverages will be covered by the sponsors.

**Comment by annapiera** [comment]
ROOMS [BOX]
**Double room** - € 239,00 + € 3,6 city tax per attendee 
**Single room** - € 329,00 + € 3,6 city tax per attendee 


 NOTA FORMATTAZIONE: eliminiamo il prezzo piccolo totale. Lasciamo solo il prezzo totale formattato come quello per notte, aggiungendo il bold.
![image](https://user-images.githubusercontent.com/47472672/74652480-662e4f80-5186-11ea-989a-0e779cfa0b71.png)

**Comment by arialdomartini** [comment]
@annapiera  Ho corretto "Guest card Trentino" con "Trentino Guest Card", con tutte le maiuscole e con le parole nell'ordine riportato dal sito.

**Comment by arialdomartini** [comment]
>  eliminiamo il prezzo piccolo totale. Lasciamo solo il prezzo totale formattato come quello per notte, aggiungendo il bold.

aiuto, non capisco.
