### ISSUE TITLE
 Il pulsante per la registrazione deve essere rosso #7 

### ISSUE THREAD

**Issue by arialdomartini** [socrates-it-test/site-source#7]
La CTA deve essere "register now", uppercase

**Comment by arialdomartini** [comment]
@annapiera Fatto. Se Ok, chiudi pure la issue. Altrimenti, aspetto commenti

**Comment by annapiera** [comment]
Se ci passo il cursore sopra diventa giallo, invece dovrebbe rimanere rosso, ma di una tonalità più scurina per far capire che si può cliccare.
Si può? @arialdomartini

**Comment by arialdomartini** [comment]
Certo!
Quando viene selezionato lo lascio rosso?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by annapiera** [comment]
Yeppa, come gli altri bottoni.
Da giallino se li selezioni diventano giallo più scuro.
Questo rosso > rosso scuro. : )

*Anna Piera Frascella*


Il giorno sab 9 feb 2019 alle ore 17:20 Arialdo Martini <
notifications@github.com> ha scritto:

**Comment by arialdomartini** [comment]
Ok, fatto.
Ho anche spostato gli altri pulsanti un po' di più a sinistra, in modo che rimangano distanti. Quando era selezionato Sponsor, rimanevano illuminati Sponsor di giallo e Register now di rosso, uno accanto all'altro, e l'effetto confondeva. Se vuoi li sposto ancora di più.

![screen shot 2019-02-09 at 21 23 29](https://user-images.githubusercontent.com/150719/52525894-fce14a00-2cb0-11e9-9f03-b2843c3be424.png)

**Comment by annapiera** [comment]
Chiudere, prego! 
@arialdomartini
