### ISSUE TITLE
Cookie banner

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#70]
Ho aggiornato il cookie banner, non mi odiare.

 Copy this script and insert it to the header of your website template to enable the consent banner. 

```
<script id="Cookiebot" src="https://consent.cookiebot.com/uc.js" data-cbid="5ca5fcef-5e0b-4402-b98e-23ae7f4d089f" type="text/javascript" async></script>
```

 Copy this script and insert it in the HTML on the specific page and at the exact position where you would like the Cookie Declaration to appear. 

```
<script id="CookieDeclaration" src="https://consent.cookiebot.com/5ca5fcef-5e0b-4402-b98e-23ae7f4d089f/cd.js" type="text/javascript" async></script>
```

**Comment by arialdomartini** [comment]
Vedo che il codice è identico a quello dello scorso anno.
Penso che le modifiche che hai apportato siano tutte lato server Cookiebot, e che lato nostro non ci sia bisogno di altro.
