### ISSUE TITLE
Form Registrazione / Cambio link PP

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#72]
L'hypelink deve puntare qui: https://www.socrates-conference.it/privacy-policy/ al posto del link attuale (è quello del sito di test).

![image](https://user-images.githubusercontent.com/47472672/75050413-38217600-54cc-11ea-8893-22648573d205.png)

**Comment by arialdomartini** [comment]
Il link è relativo: una volta sul sito finale il link punterà alla pagina produttiva.
