### ISSUE TITLE
Form registrazione / bottone

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#73]
Il bottone del form di registrazione, questo:
![image](https://user-images.githubusercontent.com/47472672/75050538-7323a980-54cc-11ea-8a46-0b104d08fe96.png)
Dovrebbe essere formattato come il bottone dell'anno scorso.
![image](https://user-images.githubusercontent.com/47472672/75050567-80409880-54cc-11ea-8d7f-ab903d8c5ed8.png)
Specifiche:
bottone rosso con scritta bianca "REGISTER NOW"
Quando ci passi sopra il bottone diventa verde con scritta bianca identica

**Comment by arialdomartini** [comment]
Ok. Ripristinato. Era scomparso avendo fatto il copia/incolla dal codice della form. Dovrebbe essere tornato esattamente come quello dello scorso anno.

**Comment by annapiera** [comment]
Lo vedo ancora grigio... 
![FD4658CE-EFAE-4A96-AB37-5C0885598CDE](https://user-images.githubusercontent.com/47472672/75089989-9860f800-555e-11ea-8f3e-d60f8026ea1e.jpeg)

**Comment by arialdomartini** [comment]
Mannaggia, io non riesco a riprodurlo...
Tu hai provato sia da iPhone che da iPad?

**Comment by annapiera** [comment]
Dall’iphone con Safari.
Tu lo vedi rosso @arialdomartini?

**Comment by annapiera** [comment]
![image](https://user-images.githubusercontent.com/47472672/75099522-de4fa780-55c2-11ea-8ace-275fedc28f65.png)
Anche da PC, Safari.

**Comment by annapiera** [comment]
@VenomAV Questa è da risolvere ancora.

**Comment by arialdomartini** [comment]
Corretto da @VenomAV
