### ISSUE TITLE
Link CP e PP

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#76]
I link della CP e della PP in basso:
![image](https://user-images.githubusercontent.com/47472672/75051177-afa3d500-54cd-11ea-9b5c-482534b01f19.png)

Linkano al sito test. Si reindirizzano da soli con il sito pubblicato o rimangono ancorati al sito di test?

**Comment by arialdomartini** [comment]
Yes! Sono link relativi: nel sito produttivo punteranno al sito produttivo.
