### ISSUE TITLE
Pagina di registrazione/ box "what is it included in the cost?" da riformattare

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#77]
![image](https://user-images.githubusercontent.com/47472672/75051366-0d382180-54ce-11ea-9372-f331f88b0bab.png)
Il testo ha perso la formattazione, totalmente.

Dovrebbe avere la grandezza di quello dello scorso anno:
![image](https://user-images.githubusercontent.com/47472672/75051468-3953a280-54ce-11ea-9b89-ae3a310dfd01.png)

Ti inserisco qui sotto i bold (Avevo dimenticato, ops!):

**[note: lascia qualche riga di spazio tra la mappa e la prima frase]**
**What is it included in the cost?**

- **Two nights full-board:** breakfast, lunch, dinner and snack buffet all day (vegetarian and gluten-free food included!)
- The hotel has both twin or double rooms. If there is someone you are willing to share the room with, feel free to book the double room. If you don’t know anyone, don’t worry: sign in the[ Sofware Crafters #italian channel on Slack](http://bit.ly/SlackSocrates) and find a suitable roommate
- City tax
- Access to the **wellness area**: indoor pool, heated outdoor pool, and wet area
- Access to the **gym** with cardio and fitness equipment
- **[Trentino Guest Card](https://www.visittrentino.info/en/experience/trentino-guest-card)**: free circulation on public transport within Trentino and free or discounted entry to over 60 museums, 20 castles, and 20 attractions
- Use of **mountain bikes**

The unconference’s beverages will be covered by the sponsors.

**[note:sotto lascia qualche riga tra l'ultima frase e il box]**

**Comment by arialdomartini** [comment]
Ok.
Contestualmente, ho cambiato da "What is it included..." a "What is included".

**Comment by annapiera** [comment]
Non vedo i cambiamenti. è normale?

*Anna Piera Frascella*


Il giorno ven 21 feb 2020 alle ore 18:19 Arialdo Martini <
notifications@github.com> ha scritto:

**Comment by arialdomartini** [comment]
Ho aggiunto anche degli spazi dopo beds, prima della mappa.

**Comment by annapiera** [comment]
@arialdomartini , perfetto!

Puoi aggiungere un dettaglio?
Gli hiperlink di questo testo possono aprirsi in un'altra tab?

Ce ne sono due:
- Sofware Crafters #italian channel on Slack
- Trentino Guest Card

**Comment by arialdomartini** [comment]
Ok. Ho applicato la stessa logica anche a tutti gli altri link esterni (per esempio, quelli degli altri eventi SoCraTes)

**Comment by arialdomartini** [comment]
(apri pure issue separate per task extra, facilita il tracking di cosa sia stato fatto e cosa no)

**Comment by annapiera** [comment]
Yap. Sarà fatto.
Non appena pubblichi controllo.

**Comment by annapiera** [comment]
Bravone! Grazie!
