### ISSUE TITLE
Change site title and og:title

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#78]
L'attuale title del sito è "This event is about the sustainable creation of useful software in a responsible way.".

Puoi cambiarla in "SoCraTes IT"?

More info: 
![image](https://user-images.githubusercontent.com/47472672/75053036-e7f8e280-54d0-11ea-9179-c87ff89c0f6d.png)

**Comment by arialdomartini** [comment]
Ok. Ho cambiato sia `og:title` che il titolo del sito (quello visibile nella barra del titolo del browser)
