### ISSUE TITLE
 Cambiare tutti i font con Helvetica Neue #8 

### ISSUE THREAD

**Issue by arialdomartini** [socrates-it-test/site-source#8]

**Comment by annapiera** [comment]
#8 Eliminare tutti i corsivi

**Comment by arialdomartini** [comment]
Ho impostato il font a Helvetica Neue. Non vedo differenze. Tu?

Ho rimosso tutti gli italici.

**Comment by annapiera** [comment]
Il nome "SOCRATES IT" è ancora in corsivo nel Menu...

Poi c'è questo droid serif un attimo fastidioso
![image](https://user-images.githubusercontent.com/47472672/52536556-5eaabe00-2d5c-11e9-805e-c731b5edbf18.png)

**Comment by arialdomartini** [comment]
Rimossi i font Droid Serif e Kaushan Script

**Comment by annapiera** [comment]
@arialdomartini chiuda, prego! :)
