### ISSUE TITLE
Registration/Box "rooms" > change cost

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#81]
Mi sono resa conto che non ha molto senso scrivere il prezzo della city tax a parte.

Quindi bisogna cambiare la dicitura nel testo del nella pagina Registration/Box "rooms":

"€239,00 + € 3,6 city tax per attendee" diventerà "€ 242,6 per attendee"

"€329,00 + € 3,6 city tax per attendee" diventerà "€ 332,6 per attendee"

**Comment by arialdomartini** [comment]
Ok. Ho scritto `242,60`, con 2 cifre decimali.
