### ISSUE TITLE
Il prezzo non si vede da mobile 

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#82]
![4B53B406-94AE-4B31-8861-85ADD1FFDEE7](https://user-images.githubusercontent.com/47472672/75089940-196bbf80-555e-11ea-92d2-f42d1b81f367.png)
Allego foto dettaglio del prezzo. Da mobile è impossibile da capire. Riusciamo a sistemare?

**Comment by arialdomartini** [comment]
L'ho sistemato un po' malamente.
In generale, quella tabella mi piace poco poco, men che mai su mobile. Ma ho visto che anche lo scorso anno non era bella. Prima o poi dovremmo dargli un restyling più definitivo...

**Comment by annapiera** [comment]
Ora almeno si vede il prezzo. Confermo! 
Troverò qualcosa di più funzionale. Ma poi.
