### ISSUE TITLE
Change og:image / registration page

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#83]
L'immagine della pagina registration attualmente è il logo del socrates, questo viene visualizzato a metà quindi non è gradevole
Dettagli: 

![image](https://user-images.githubusercontent.com/47472672/75091269-a9fccc80-556b-11ea-899f-5a44a97626be.png)

Puoi cambiarlo con questa: https://socrates-it-test.github.io/img/header-bg.jpg ?

**Comment by VenomAV** [comment]
@arialdomartini non so come rendere visibili le modifiche ad @annapiera. Ci puoi pensare tu?
