### ISSUE TITLE
Change og:title / registration page

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#84]
Il nuovo og:title della registration page sarà: "SoCraTes IT - Registration"

Dettagli attuali:
![image](https://user-images.githubusercontent.com/47472672/75091298-0f50bd80-556c-11ea-9388-e27c0ef162b2.png)

**Comment by arialdomartini** [comment]
Anna, ho un po' di difficoltà a fare questa e la #83: di default su Hugo le meta informazioni sono in comune a tutte le pagine. Di sicuro posso fare un barbatrucco, ma non in 5 minuti. Adesso guardo come fare...

**Comment by arialdomartini** [comment]
Trovato. Dovrei essere in grado di ottenere quello che chiedi usando

https://gohugo.io/variables/page/#the-param-method

Lo segno qui come reminder.
@annapiera, tu nel frattempo chiudi tutte le issue che sono verificate sul sito di test?

**Comment by annapiera** [comment]
Non è di vitale importanza, ma se su Hugo prende la stessa descrizione su tutte le pagine perché come immagine sulla pagina di registrazione mi esce il logo? 

Mettiamola pure in standby questa issue.

**Comment by VenomAV** [comment]
@arialdomartini non so come rendere visibili le modifiche ad @annapiera. Ci puoi pensare tu?
