### ISSUE TITLE
Form registration - eliminare ultima frase

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#91]
La frase del form: "You can change your mind at any time by clicking the unsubscribe link in the footer of any email you receive from us." è da eliminare totalmente.

Qui:
![image](https://user-images.githubusercontent.com/47472672/75186461-3663e680-5748-11ea-890b-c183e3fd36eb.png)

**Comment by arialdomartini** [comment]
Grazie @annapiera. Super comodo avere issue così puntuali.
