### ISSUE TITLE
Eliminare scritta sotto immagine homepage 

### ISSUE THREAD

**Issue by annapiera** [socrates-it-test/site-source#95]
Precisamente: eliminare la scritta dei credits sotto l’immagine dell’homepage

**Comment by arialdomartini** [comment]
In quella posizione non funziona, soprattutto da mobile. Ma mi sembra di aver capito che l'attribuzione ci voglia. Sarebbe da capire bene se debba stare insieme all'immagine o no.

**Comment by arialdomartini** [comment]
Ok, tolta. Ma va rimessa altrove.

**Comment by arialdomartini** [comment]
Ok, vista la issue #94.
Dobbiamo prendere una decisione sull'immagine di home page.
